language: ruby
branches:
  only:
    - master
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.4
  - 2.3.0
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
  - jruby-head

before_install:
  - which bundle >/dev/null 2>&1 || gem install bundler

matrix:
  allow_failures:
      - rvm: ruby-head
      - rvm: jruby-head
